name: Deploy to Production

on:
  workflow_run:
    workflows:
      - "Run E2E test"
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Link to the environment
        run: railway environment production
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_PRODUCTION_TOKEN }}

      - name: Deploy
        run: railway up --ci  --service fastify-webapp-sample
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_PRODUCTION_TOKEN }}
